### ISSUE TITLE
Illegal division by zero at /usr/bin/termpub line 237.

### ISSUE THREAD

**Issue by Peter200lx** [mdom/termpub#2]
I'm running termpub 1.03-1 from AUR on Archlinux. With some files I get the div by zero error.

https://github.com/mdom/termpub/blob/87e11723118c5f0b8873ded1ec668ac13f31f4d5/lib/App/termpub/Pager.pm#L234-L238

For an example file with this issue, I'm hitting it with `rationality.epub` from http://www.hpmor.com/

**Comment by Peter200lx** [comment]
Ah, nevermind, this is fixed in 1.04 with commit 87e11723118c5f0b8873ded1ec668ac13f31f4d5 . I'll create an account to flag the AUR package as out of date.

**Comment by mdom** [comment]
Thanks for reporting that issue! Sure, just open a new issue for the percentage. I'm currently on vacation but I'll take a look as soon as possible. Cheers, Mario
